/* TrailLink is deliberately dependency-light: KML parsing and route construction stay in this browser. */
const $ = (s) => document.querySelector(s);
const state = { points: [], splits: [], map: null, original: null, generated: [], splitLayers: [] };
const colors = ['#ef6b55','#477bdf','#8f55b7','#d49a29','#198c78','#e45c98','#626dc4'];

function distance(a,b){ const r=6371000, dLat=(b.lat-a.lat)*Math.PI/180,dLng=(b.lng-a.lng)*Math.PI/180; const x=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLng/2)**2; return 2*r*Math.asin(Math.sqrt(x)); }
function perpendicularDistance(p,a,b){ const x=p.lng,y=p.lat,x1=a.lng,y1=a.lat,x2=b.lng,y2=b.lat,dx=x2-x1,dy=y2-y1; if(!dx&&!dy)return Math.hypot(x-x1,y-y1); const t=Math.max(0,Math.min(1,((x-x1)*dx+(y-y1)*dy)/(dx*dx+dy*dy))); return Math.hypot(x-(x1+t*dx),y-(y1+t*dy))*111000; }
function simplify(pts,tolerance){ if(pts.length<3)return pts; let max=0,index=0; for(let i=1;i<pts.length-1;i++){const d=perpendicularDistance(pts[i],pts[0],pts.at(-1));if(d>max){max=d;index=i;}} return max>tolerance?[...simplify(pts.slice(0,index+1),tolerance).slice(0,-1),...simplify(pts.slice(index),tolerance)]:[pts[0],pts.at(-1)]; }
function nearestIndex(latlng){ let best=0,bestD=Infinity; state.points.forEach((p,i)=>{const d=distance(p,latlng);if(d<bestD){bestD=d;best=i;}}); return best; }
function segments(){ const ends=[...state.splits, state.points.length-1]; let start=0; return ends.map(end=>{const part=state.points.slice(start,end+1);start=end;return part;}).filter(p=>p.length>1); }
function routePoints(part){ const level=+$('#strictness').value; const tolerances=[220,100,45,18,5]; return simplify(part,tolerances[level-1]); }
function makeRoutes(){ const max=+$('#waypoints').value; const result=[]; segments().forEach(part=>{let p=routePoints(part); // automatic chunks preserve the selected manual boundaries
  while(p.length>max+2){ result.push(p.slice(0,max+2)); p=p.slice(max+1); } result.push(p);
 }); return result; }
function urlFor(points){ const origin=`${points[0].lat},${points[0].lng}`, destination=`${points.at(-1).lat},${points.at(-1).lng}`; const stops=points.slice(1,-1).map(p=>`${p.lat},${p.lng}`).join('|'); return `https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(origin)}&destination=${encodeURIComponent(destination)}&travelmode=driving${stops?`&waypoints=${encodeURIComponent(stops)}`:''}`; }
function render(){ if(!state.points.length)return; const routes=makeRoutes(); $('#route-count').textContent=routes.length; state.generated.forEach(l=>state.map.removeLayer(l));state.generated=[];state.splitLayers.forEach(l=>state.map.removeLayer(l));state.splitLayers=[];
 const bounds=[]; if(state.original)state.map.removeLayer(state.original); state.original=L.polyline(state.points,{color:'#65716e',weight:3,opacity:.75,dashArray:'7 7'}).addTo(state.map); bounds.push(...state.points);
 routes.forEach((route,i)=>{state.generated.push(L.polyline(route,{color:colors[i%colors.length],weight:4,opacity:.9}).addTo(state.map));});
 state.splits.forEach((idx,i)=>{const icon=L.divIcon({className:'',html:`<div class="split-marker">${i+1}</div>`,iconSize:[25,25],iconAnchor:[12,12]});const m=L.marker(state.points[idx],{icon,draggable:true}).addTo(state.map);m.on('dragend',e=>{state.splits[i]=nearestIndex(e.target.getLatLng());normalizeSplits();render();});m.on('click',()=>{state.splits.splice(i,1);render();});state.splitLayers.push(m);});
 $('#route-list').replaceChildren();const template=$('#route-template');routes.forEach((route,i)=>{const node=template.content.firstElementChild.cloneNode(true),url=urlFor(route);node.querySelector('.route-swatch').style.background=colors[i%colors.length];node.querySelector('strong').textContent=`Route ${i+1}`;node.querySelector('small').textContent=`${route.length-2} waypoint${route.length===3?'':'s'} · ${Math.round(route.reduce((sum,p,j)=>j?sum+distance(route[j-1],p):sum,0)/1000*10)/10} km`;const a=node.querySelector('a');a.href=url;a.dataset.url=url;node.querySelector('.copy-url').onclick=()=>copy(url,node.querySelector('.copy-url'));$('#route-list').append(node);});
 }
function normalizeSplits(){state.splits=[...new Set(state.splits.filter(i=>i>1&&i<state.points.length-2))].sort((a,b)=>a-b);}
function copy(text,button){navigator.clipboard.writeText(text).then(()=>{const old=button.textContent;button.textContent='Copied!';setTimeout(()=>button.textContent=old,1200);});}
function loadKml(file){const reader=new FileReader();reader.onload=()=>{try{const xml=new DOMParser().parseFromString(reader.result,'application/xml');if(xml.querySelector('parsererror'))throw Error('Invalid XML');const raw=[...xml.querySelectorAll('LineString coordinates, gx\\:Track coordinates, coordinates')].flatMap(n=>n.textContent.trim().split(/\s+/));const points=[];raw.forEach(s=>{const [lng,lat]=s.split(',').map(Number);if(Number.isFinite(lat)&&Number.isFinite(lng)&&(!points.length||lat!==points.at(-1).lat||lng!==points.at(-1).lng))points.push({lat,lng});});if(points.length<2)throw Error('No track coordinates found');state.points=points;state.splits=[];$('#track-points').textContent=points.length;$('#map-title').textContent=file.name.replace(/\.kml$/i,'');$('#empty-state').hidden=true;$('#workspace').hidden=false; if(!state.map){state.map=L.map('map',{zoomControl:false}).setView([points[0].lat,points[0].lng],12);L.control.zoom({position:'bottomright'}).addTo(state.map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(state.map);state.map.on('click',e=>{state.splits.push(nearestIndex(e.latlng));normalizeSplits();render();});}render();state.map.fitBounds(L.latLngBounds(state.points),{padding:[35,35]});}catch(e){alert(`Could not read this KML: ${e.message}`);}};reader.readAsText(file);}
$('#kml-file').addEventListener('change',e=>e.target.files[0]&&loadKml(e.target.files[0]));document.querySelector('.upload').addEventListener('dragover',e=>{e.preventDefault();e.currentTarget.style.background='#e9f5d1';});document.querySelector('.upload').addEventListener('dragleave',e=>e.currentTarget.style.background='');document.querySelector('.upload').addEventListener('drop',e=>{e.preventDefault();e.currentTarget.style.background='';e.dataTransfer.files[0]&&loadKml(e.dataTransfer.files[0]);});
const labels=['Loose','Relaxed','Balanced','Strict','Exact'];['waypoints','strictness'].forEach(id=>$('#'+id).addEventListener('input',e=>{$('#'+id+'-out').textContent=id==='waypoints'?e.target.value:labels[e.target.value-1];render();}));$('#clear-splits').onclick=()=>{state.splits=[];render();};$('#copy-all').onclick=()=>copy([...document.querySelectorAll('.route-info a')].map(a=>a.dataset.url).join('\n'),$('#copy-all'));
