const $ = (s) => document.querySelector(s);
const colors = ['#ef6b55','#477bdf','#8f55b7','#d49a29','#198c78','#e45c98','#626dc4'];
const state = { points: [], placemarks: [], manualSplits: [], map: null, original: null, generated: [], splitLayers: [], placemarkLayers: [] };

function distance(a,b) { const r=6371000,dLat=(b.lat-a.lat)*Math.PI/180,dLng=(b.lng-a.lng)*Math.PI/180,x=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLng/2)**2; return 2*r*Math.asin(Math.sqrt(x)); }
function pointDistance(p,a,b) { const x=p.lng,y=p.lat,x1=a.lng,y1=a.lat,x2=b.lng,y2=b.lat,dx=x2-x1,dy=y2-y1;if(!dx&&!dy)return Math.hypot(x-x1,y-y1)*111000;const t=Math.max(0,Math.min(1,((x-x1)*dx+(y-y1)*dy)/(dx*dx+dy*dy)));return Math.hypot(x-(x1+t*dx),y-(y1+t*dy))*111000; }
function simplify(pts,t) { if(pts.length<3)return pts;let max=0,index=0;for(let i=1;i<pts.length-1;i++){const d=pointDistance(pts[i],pts[0],pts.at(-1));if(d>max){max=d;index=i;}}return max>t?[...simplify(pts.slice(0,index+1),t).slice(0,-1),...simplify(pts.slice(index),t)]:[pts[0],pts.at(-1)]; }
function nearestIndex(latlng) { let best=0,bestD=Infinity;state.points.forEach((p,i)=>{const d=distance(p,latlng);if(d<bestD){bestD=d;best=i;}});return best; }
function mode() { return document.querySelector('[name="split-mode"]:checked').value; }
function splitIndices() { if(mode()==='manual')return state.manualSplits;if(mode()==='placemarks')return state.placemarks.map(p=>nearestIndex(p)).filter(i=>i>1&&i<state.points.length-2);const count=+$('#auto-splits-input').value;return Array.from({length:count},(_,i)=>Math.round((i+1)*(state.points.length-1)/(count+1))); }
function normalizedSplits() { return [...new Set(splitIndices())].sort((a,b)=>a-b); }
function segments() { const ends=[...normalizedSplits(),state.points.length-1];let start=0;return ends.map(end=>{const out=state.points.slice(start,end+1);start=end;return out;}).filter(p=>p.length>1); }
function filterSpacing(points) { const minimum=+$('#spacing').value;if(!minimum)return points;const result=[points[0]];for(let i=1;i<points.length-1;i++)if(distance(result.at(-1),points[i])>=minimum)result.push(points[i]);if(result.at(-1)!==points.at(-1))result.push(points.at(-1));return result; }
function sample(points,max) { if(points.length<=max+2)return points;return Array.from({length:max+2},(_,i)=>points[Math.round(i*(points.length-1)/(max+1))]); }
function makeRoutes() { const tolerance=[220,100,45,18,5][+$('#strictness').value-1],max=+$('#waypoints').value;return segments().map(part=>sample(filterSpacing(simplify(part,tolerance)),max)); }
function urlFor(points) { const origin=`${points[0].lat},${points[0].lng}`,destination=`${points.at(-1).lat},${points.at(-1).lng}`,stops=points.slice(1,-1).map(p=>`${p.lat},${p.lng}`).join('|');return `https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(origin)}&destination=${encodeURIComponent(destination)}&travelmode=driving${stops?`&waypoints=${encodeURIComponent(stops)}`:''}`; }
function clearLayers(layers) { layers.forEach(layer=>state.map.removeLayer(layer));return []; }
function renderPlacemarks() { state.placemarkLayers=clearLayers(state.placemarkLayers);const list=$('#placemark-list');list.replaceChildren();if(!state.placemarks.length){list.textContent='No point placemarks found in this KML.';return;}state.placemarks.forEach(p=>{const marker=L.circleMarker(p,{radius:6,color:'#17312c',weight:2,fillColor:'#c8f169',fillOpacity:1}).bindTooltip(p.name,{permanent:true,direction:'top',offset:[0,-7],className:'placemark-label'}).addTo(state.map);state.placemarkLayers.push(marker);const item=document.createElement('div'),title=document.createElement('b'),coords=document.createElement('small');item.className='placemark';title.textContent=p.name;coords.textContent=`${p.lat.toFixed(5)}, ${p.lng.toFixed(5)}`;item.append(title,coords);item.onclick=()=>state.map.flyTo(p,15);list.append(item);}); }
function render() { if(!state.points.length)return;const routes=makeRoutes();$('#route-count').textContent=routes.length;state.generated=clearLayers(state.generated);state.splitLayers=clearLayers(state.splitLayers);if(state.original)state.map.removeLayer(state.original);state.original=L.polyline(state.points,{color:'#65716e',weight:3,opacity:.75,dashArray:'7 7'}).addTo(state.map);routes.forEach((route,i)=>state.generated.push(L.polyline(route,{color:colors[i%colors.length],weight:4,opacity:.9}).addTo(state.map)));if(mode()==='manual')normalizedSplits().forEach((idx,i)=>{const icon=L.divIcon({className:'',html:`<div class="split-marker">${i+1}</div>`,iconSize:[25,25],iconAnchor:[12,12]});const marker=L.marker(state.points[idx],{icon,draggable:true}).addTo(state.map);marker.on('dragend',e=>{state.manualSplits[i]=nearestIndex(e.target.getLatLng());state.manualSplits=normalizedSplits();render();});marker.on('click',()=>{state.manualSplits.splice(i,1);render();});state.splitLayers.push(marker);});$('#route-list').replaceChildren();const template=$('#route-template');routes.forEach((route,i)=>{const node=template.content.firstElementChild.cloneNode(true),url=urlFor(route),kms=Math.round(route.reduce((sum,p,j)=>j?sum+distance(route[j-1],p):sum,0)/100)/10;node.querySelector('.route-swatch').style.background=colors[i%colors.length];node.querySelector('strong').textContent=`Route ${i+1}`;node.querySelector('small').textContent=`${route.length-2} waypoint${route.length===3?'':'s'} · ${kms} km`;const a=node.querySelector('a');a.href=url;a.dataset.url=url;node.querySelector('.copy-url').onclick=()=>copy(url,node.querySelector('.copy-url'));$('#route-list').append(node);});updateModeHelp(); }
function updateModeHelp() { const current=mode(),auto=$('#auto-splits'),count=normalizedSplits().length;auto.hidden=current!=='automatic';$('#split-note').textContent=current==='automatic'?`Creates up to ${count} evenly placed split${count===1?'':'s'}.`:current==='placemarks'?`${count} on-track placemark${count===1?'':'s'} will be used as split${count===1?'':'s'}.`:`${count} manual split${count===1?'':'s'} placed on the track.`; }
function copy(text,button) { navigator.clipboard.writeText(text).then(()=>{const old=button.textContent;button.textContent='Copied!';setTimeout(()=>button.textContent=old,1200);}); }
function parseCoordinates(text) { return text.trim().split(/\s+/).map(s=>s.split(',').map(Number)).map(([lng,lat])=>({lat,lng})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lng)); }
function loadKml(file) { const reader=new FileReader();reader.onload=()=>{try { const xml=new DOMParser().parseFromString(reader.result,'application/xml');if(xml.querySelector('parsererror'))throw Error('Invalid XML');const tracks=[...xml.querySelectorAll('LineString > coordinates')].map(n=>parseCoordinates(n.textContent)).filter(p=>p.length>1);if(!tracks.length)throw Error('No LineString track found');state.points=tracks.sort((a,b)=>b.length-a.length)[0];state.placemarks=[...xml.querySelectorAll('Placemark')].flatMap((node,i)=>{const coordinate=node.querySelector('Point > coordinates');if(!coordinate)return [];const [p]=parseCoordinates(coordinate.textContent);return p?[{...p,name:node.querySelector('name')?.textContent.trim()||`Placemark ${i+1}`}]:[];});state.manualSplits=[];$('#track-points').textContent=state.points.length;$('#map-title').textContent=file.name.replace(/\.kml$/i,'');$('#empty-state').hidden=true;$('#workspace').hidden=false;if(!state.map){state.map=L.map('map',{zoomControl:false}).setView(state.points[0],12);L.control.zoom({position:'bottomright'}).addTo(state.map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(state.map);state.map.on('click',e=>{if(mode()!=='manual')return;state.manualSplits.push(nearestIndex(e.latlng));state.manualSplits=normalizedSplits();render();});}renderPlacemarks();render();state.map.fitBounds(L.latLngBounds([...state.points,...state.placemarks]),{padding:[35,35]});}catch(e){alert(`Could not read this KML: ${e.message}`);}};reader.readAsText(file); }
$('#kml-file').addEventListener('change',e=>e.target.files[0]&&loadKml(e.target.files[0]));document.querySelector('.upload').addEventListener('dragover',e=>{e.preventDefault();e.currentTarget.style.background='#e9f5d1';});document.querySelector('.upload').addEventListener('dragleave',e=>e.currentTarget.style.background='');document.querySelector('.upload').addEventListener('drop',e=>{e.preventDefault();e.currentTarget.style.background='';e.dataTransfer.files[0]&&loadKml(e.dataTransfer.files[0]);});
const labels=['Loose','Relaxed','Balanced','Strict','Exact'];['waypoints','strictness','spacing','auto-splits-input'].forEach(id=>$('#'+id).addEventListener('input',e=>{if(id==='waypoints')$('#waypoint-out').textContent=e.target.value;if(id==='strictness')$('#strictness-out').textContent=labels[e.target.value-1];if(id==='spacing')$('#spacing-out').textContent=e.target.value==='0'?'Off':`${e.target.value} m`;if(id==='auto-splits-input')$('#auto-splits-out').textContent=e.target.value;render();}));document.querySelectorAll('[name="split-mode"]').forEach(input=>input.addEventListener('change',render));$('#clear-splits').onclick=()=>{state.manualSplits=[];render();};$('#copy-all').onclick=()=>copy([...document.querySelectorAll('.route-info a')].map(a=>a.dataset.url).join('\n'),$('#copy-all'));
